### ISSUE TITLE
Is this actually the 2016 entry?

### ISSUE THREAD

**Issue by cjdrake** [msoos/glucose2016#1]
The initial checkin looks identical to:
http://baldur.iti.kit.edu/sat-competition-2016/solvers/parallel16/syrup.zip

I couldn't find the 2015 source code for comparison, but the 2016 proceedings seem to indicate there was some difference from the previous year.

**Comment by msoos** [comment]
Crap you are right. It is. Let me rename it :)

**Comment by msoos** [comment]
Thanks, it was pretty easy to fix actually :)
